"""A custom definition becomes something a person can authorize (1.7).

One table. An authorization already says who may hold a definition;
this says the definition itself is supposed to exist and look like
this, bound to the hash of the contents that were agreed. It is the
record that lets the delta report a custom policy nobody authorized,
and a custom policy whose contents moved after somebody did.

Written by hand rather than autogenerated, so the columns are exactly
the model's and the alembic check in the pipeline holds the two to each
other.

Conditional on purpose. Revision 0001 creates every table the models
declare, which was the greenfield decision (D-071) and means a fresh
database already has this table by the time 0002 runs, while a database
upgraded before this table existed does not. Creating it only when it
is absent makes both arrive at the same place, and the check in the
pipeline proves they did. Every table added from here on carries the
same guard until 0001 is frozen to an explicit list.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-29
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    if sa.inspect(bind).has_table("authorized_role_definitions"):
        return
    op.create_table(
        "authorized_role_definitions",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column(
            "provider_id", sa.Integer(), sa.ForeignKey("providers.id"), nullable=False
        ),
        sa.Column("role_definition_external_id", sa.String(2048), nullable=False),
        sa.Column("role_definition_hash", sa.String(64), nullable=False),
        sa.Column("display_name", sa.String(255), nullable=False),
        sa.Column("owner_kind", sa.String(16), nullable=False),
        sa.Column("owner_ref", sa.String(255), nullable=False),
        sa.Column("authorizer_user_id", sa.Integer(), nullable=True),
        sa.Column("authorizer_username", sa.String(64), nullable=False),
        sa.Column("authorized_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("justification", sa.String(1000), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column(
            "supersedes_id",
            sa.Integer(),
            sa.ForeignKey("authorized_role_definitions.id"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_authorized_role_definitions_provider_id",
        "authorized_role_definitions",
        ["provider_id"],
    )


def downgrade() -> None:
    op.drop_index(
        "ix_authorized_role_definitions_provider_id",
        table_name="authorized_role_definitions",
    )
    op.drop_table("authorized_role_definitions")
